name: "Poetry export requirements.txt file"
description: "Export requirements.txt file from poetry"
inputs:
  without-hashes:
    description: Export requirements.txt file without-hashes
    required: false
    default: "true"
  outfile-name:
    description: Name of the output file
    required: false
    default: "requirements.txt"
  args:
    description: Additional args to pass to poetry
    required: false
    default: ""
outputs:
  custom-file-name:
    description: Name of the output file
    value: ${{ inputs.outfile-name }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v3

    - run: |-
        python -m pip install poetry
      shell: bash

    - run: |-
        poetry self add poetry-plugin-export
      shell: bash

    - if: inputs.without-hashes == 'true'
      run: |-
        poetry export -f requirements.txt ${{ inputs.args }} --without-hashes --output ${{ inputs.outfile-name }}
      shell: bash

    - if: inputs.without-hashes == 'false'
      run: |-
        poetry export -f requirements.txt ${{ inputs.args }} --output ${{ inputs.outfile-name }}
      shell: bash

branding:
  icon: code
  color: blue
